import React from "react";
import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0F1C] text-gray-200 flex flex-col">
      <Navbar />

      <main className="max-w-4xl mx-auto px-4 py-20 space-y-10">
        <h1 className="text-4xl font-bold text-white">Terms of Service</h1>
        <p className="text-gray-400">Effective Date: January 2025</p>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of
          the ER Simulator platform operated by Tjomsland LLC, doing business as
          (&quot;DBA&quot;) ER Simulator (&quot;we&quot;, &quot;us&quot;).
        </p>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Overview</h2>
          <p>
            ER Simulator provides AI-powered emergency medicine training
            simulations. By using our service, you agree to these Terms. You
            acknowledge that ER Simulator is for <strong>educational use only</strong>.
            It must not be used for diagnosis, treatment, or real patient care.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. Not Medical Advice</h2>
          <p>
            ER Simulator provides fictional and simulated content generated by
            AI. It is not medical advice and must not be used to make clinical
            decisions. All medical questions should be directed to appropriate
            licensed professionals.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. Accounts & Access</h2>
          <p>
            You may need to create an account and purchase a subscription through
            Paddle or Apple. You must provide accurate information and maintain
            account security. We reserve the right to suspend accounts for misuse.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. Subscriptions & Payments</h2>
          <p>
            Payments are processed securely via Paddle or the Apple App Store.
            Subscriptions renew automatically unless canceled. Prices may change
            with notice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">5. Licensing & Restrictions</h2>
          <p>
            You receive a limited, non-exclusive, non-transferable license to use
            ER Simulator. You may not copy, resell, misuse, or use the service to
            make medical decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">6. Intellectual Property</h2>
          <p>
            All content, design, and code are owned by Tjomsland LLC. Users may
            not reproduce platform materials without permission.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">7. AI-Generated Content</h2>
          <p>
            AI outputs may contain inaccuracies. We do not guarantee correctness
            or adherence to medical guidelines. You agree not to rely on simulations
            for real clinical actions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">8. Limitation of Liability</h2>
          <p>
            ER Simulator is provided &quot;as is&quot;. We are not liable for any damages,
            including those related to reliance on simulation content or system
            downtime.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">9. Refunds</h2>
          <p>
            Refunds are handled by the payment provider (Paddle or Apple). See our{" "}
            <a href="/refund" className="text-teal-400 underline">Refund Policy</a>.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">10. Contact</h2>
          <p>Tjomsland LLC (DBA ER Simulator)</p>
          <p>Email: support@ersimulator.com</p>
          <p>USA</p>
        </section>
      </main>

      <Footer />
    </div>
  );
}